Update Cargo.lock
Fixes the following error:

```
    Updating git repository `https://github.com/rtic-rs/cortex-m-rtic.git`
error: failed to get `rtic` as a dependency of package `pico-probe v0.1.0 (/home/jan/tmp/rusty-probe-firmware)`

Caused by:
  failed to load source for dependency `rtic`

Caused by:
  Unable to update https://github.com/rtic-rs/cortex-m-rtic.git?branch=rticv2#6c73c345

Caused by:
  object not found - no match for id (6c73c3452a1924c713973b2262d4b09838426e02); class=Odb (9); code=NotFound (-3)
```

It looks like the version in Cargo.lock is no longer available from
github, for some reason?